-- Canonical keys/placement from the core task's 2026-09-09 command inventories.
-- No GM aliases, coordinates, local discovery claims or cached arrival authority.
ManTechPB_Destinations = {
    {key="ragefire_chasm",label="Ragefire Chasm",note="Inside.",first=1,last=3},
    {key="deadmines",label="The Deadmines",note="Outside.",first=1,last=3},
    {key="wailing_caverns",label="Wailing Caverns",note="Outside.",first=1,last=3},
    {key="shadowfang_keep",label="Shadowfang Keep",note="Outside.",first=1,last=3},
    {key="blackfathom_deeps",label="Blackfathom Deeps",note="Outside.",first=1,last=3},
    {key="stockade",label="The Stockade",note="Inside.",first=1,last=3},
    {key="gnomeregan",label="Gnomeregan",note="Outside.",first=1,last=3},
    {key="razorfen_kraul",label="Razorfen Kraul",note="Outside.",first=1,last=3},
    {key="scarlet_graveyard",label="Scarlet Monastery: Graveyard",note="Outside. Shared Scarlet Monastery approach; walk to the selected wing.",first=1,last=3},
    {key="scarlet_library",label="Scarlet Monastery: Library",note="Outside. Shared Scarlet Monastery approach; walk to the selected wing.",first=1,last=3},
    {key="scarlet_armory",label="Scarlet Monastery: Armory",note="Outside. Shared Scarlet Monastery approach; walk to the selected wing.",first=1,last=3},
    {key="scarlet_cathedral",label="Scarlet Monastery: Cathedral",note="Outside. Shared Scarlet Monastery approach; walk to the selected wing.",first=1,last=3},
    {key="razorfen_downs",label="Razorfen Downs",note="Outside.",first=1,last=3},
    {key="uldaman",label="Uldaman",note="Outside.",first=1,last=3},
    {key="zulfarrak",label="Zul'Farrak",note="Outside.",first=1,last=3},
    {key="maraudon",label="Maraudon",note="Outside.",first=1,last=3},
    {key="sunken_temple",label="The Temple of Atal'Hakkar",note="Outside.",first=1,last=3},
    {key="blackrock_depths",label="Blackrock Depths",note="Outside.",first=1,last=3},
    {key="lower_blackrock_spire",label="Lower Blackrock Spire",note="Outside.",first=1,last=3},
    {key="upper_blackrock_spire",label="Upper Blackrock Spire",note="Outside. Shared Blackrock Spire entrance; follow the normal route and requirements for the upper section.",first=1,last=3},
    {key="dire_maul_east",label="Dire Maul: East",note="Outside.",first=1,last=3},
    {key="dire_maul_west",label="Dire Maul: West",note="Outside.",first=1,last=3},
    {key="dire_maul_north",label="Dire Maul: North",note="Outside.",first=1,last=3},
    {key="scholomance",label="Scholomance",note="Outside.",first=1,last=3},
    {key="stratholme",label="Stratholme",note="Outside.",first=1,last=3},
    {key="molten_core",label="Molten Core",note="Outside. Blackrock Depths approach; follow the normal route or authorized shortcut to Molten Core.",first=1,last=3},
    {key="onyxias_lair",label="Onyxia's Lair",note="Outside. Level-60 encounter.",first=1,last=3},
    {key="blackwing_lair",label="Blackwing Lair",note="Outside. Blackrock Spire approach; follow the normal route or authorized shortcut to Blackwing Lair.",first=1,last=3},
    {key="zulgurub",label="Zul'Gurub",note="Outside.",first=1,last=3},
    {key="ruins_ahnqiraj",label="Ruins of Ahn'Qiraj",note="Outside.",first=1,last=3},
    {key="temple_ahnqiraj",label="Temple of Ahn'Qiraj",note="Outside.",first=1,last=3},
    {key="naxxramas_40",label="Naxxramas (level 60)",note="Outside.",first=1,last=2},
    {key="hellfire_ramparts",label="Hellfire Ramparts",note="Outside.",first=2,last=3},
    {key="blood_furnace",label="The Blood Furnace",note="Outside.",first=2,last=3},
    {key="shattered_halls",label="The Shattered Halls",note="Outside.",first=2,last=3},
    {key="slave_pens",label="The Slave Pens",note="Outside.",first=2,last=3},
    {key="underbog",label="The Underbog",note="Outside.",first=2,last=3},
    {key="steamvault",label="The Steamvault",note="Outside.",first=2,last=3},
    {key="mana_tombs",label="Mana-Tombs",note="Outside.",first=2,last=3},
    {key="auchenai_crypts",label="Auchenai Crypts",note="Outside.",first=2,last=3},
    {key="sethekk_halls",label="Sethekk Halls",note="Outside.",first=2,last=3},
    {key="shadow_labyrinth",label="Shadow Labyrinth",note="Outside.",first=2,last=3},
    {key="old_hillsbrad",label="Old Hillsbrad Foothills",note="Outside.",first=2,last=3},
    {key="black_morass",label="The Black Morass",note="Outside.",first=2,last=3},
    {key="mechanar",label="The Mechanar",note="Outside.",first=2,last=3},
    {key="botanica",label="The Botanica",note="Outside.",first=2,last=3},
    {key="arcatraz",label="The Arcatraz",note="Outside.",first=2,last=3},
    {key="magisters_terrace",label="Magisters' Terrace",note="Outside.",first=2,last=3},
    {key="karazhan",label="Karazhan",note="Outside.",first=2,last=3},
    {key="gruuls_lair",label="Gruul's Lair",note="Outside.",first=2,last=3},
    {key="magtheridons_lair",label="Magtheridon's Lair",note="Outside.",first=2,last=3},
    {key="serpentshrine_cavern",label="Serpentshrine Cavern",note="Outside.",first=2,last=3},
    {key="tempest_keep",label="Tempest Keep: The Eye",note="Outside.",first=2,last=3},
    {key="hyjal_summit",label="The Battle for Mount Hyjal",note="Outside.",first=2,last=3},
    {key="black_temple",label="Black Temple",note="Outside.",first=2,last=3},
    {key="zulaman",label="Zul'Aman",note="Outside.",first=2,last=3},
    {key="sunwell_plateau",label="Sunwell Plateau",note="Outside.",first=2,last=3},
    {key="utgarde_keep",label="Utgarde Keep",note="Outside.",first=3,last=3},
    {key="nexus",label="The Nexus",note="Outside.",first=3,last=3},
    {key="azjol_nerub",label="Azjol-Nerub",note="Outside.",first=3,last=3},
    {key="ahnkahet",label="Ahn'kahet: The Old Kingdom",note="Inside.",first=3,last=3},
    {key="draktharon_keep",label="Drak'Tharon Keep",note="Outside.",first=3,last=3},
    {key="violet_hold",label="The Violet Hold",note="Outside.",first=3,last=3},
    {key="gundrak",label="Gundrak",note="Outside.",first=3,last=3},
    {key="halls_of_stone",label="Halls of Stone",note="Inside.",first=3,last=3},
    {key="halls_of_lightning",label="Halls of Lightning",note="Inside.",first=3,last=3},
    {key="oculus",label="The Oculus",note="Inside.",first=3,last=3},
    {key="utgarde_pinnacle",label="Utgarde Pinnacle",note="Outside.",first=3,last=3},
    {key="culling_stratholme",label="The Culling of Stratholme",note="Outside.",first=3,last=3},
    {key="trial_champion",label="Trial of the Champion",note="Outside.",first=3,last=3},
    {key="forge_of_souls",label="The Forge of Souls",note="Inside.",first=3,last=3},
    {key="pit_of_saron",label="Pit of Saron",note="Inside.",first=3,last=3},
    {key="halls_of_reflection",label="Halls of Reflection",note="Inside.",first=3,last=3},
    {key="naxxramas",label="Naxxramas level 80",note="Outside.",first=3,last=3},
    {key="obsidian_sanctum",label="The Obsidian Sanctum",note="Outside.",first=3,last=3},
    {key="eye_of_eternity",label="The Eye of Eternity",note="Outside. Shared Nexus approach; follow the normal route to the Eye of Eternity.",first=3,last=3},
    {key="vault_archavon",label="Vault of Archavon",note="Outside. Requires Wintergrasp ownership and no active battle.",first=3,last=3},
    {key="ulduar",label="Ulduar",note="Outside.",first=3,last=3},
    {key="trial_crusader",label="Trial of the Crusader",note="Outside.",first=3,last=3},
    {key="icecrown_citadel",label="Icecrown Citadel",note="Outside.",first=3,last=3},
    {key="ruby_sanctum",label="The Ruby Sanctum",note="Outside.",first=3,last=3},
}
