-- Bundled preset names from T-imothy/playerbots 662fe10d; no server config/secrets.
return {
    {"Classic",4,"pve dps assasination"},
    {"Classic",4,"pve dps combat"},
    {"Classic",1,"pve arms"},
    {"Classic",1,"pve fury"},
    {"Classic",1,"pve prot"},
    {"Classic",1,"pvp arms"},
    {"Classic",1,"pvp fury"},
    {"Classic",1,"pvp prot"},
    {"Classic",1,"fury slam"},
    {"Classic",1,"arms axes"},
    {"Classic",1,"arms maces"},
    {"Classic",1,"arms swords"},
    {"Classic",1,"arms polearms"},
    {"Classic",1,"furyprot"},
    {"Classic",1,"furyprot (slam)"},
    {"Classic",1,"furyprot (demo shout)"},
    {"Classic",1,"2h fury"},
    {"Classic",1,"fury no deep wounds"},
    {"Classic",2,"pve dps ret (basic ret)"},
    {"Classic",2,"pve dps ret (geared ret)"},
    {"Classic",2,"pve heal holy (sanctuary)"},
    {"Classic",2,"pve heal holy (prot! holy shock taunt)"},
    {"Classic",2,"pvp heal holy"},
    {"Classic",2,"pvp heal Holy"},
    {"Classic",2,"pvp tank prot"},
    {"Classic",2,"pvp dps ret"},
    {"Classic",2,"pvp dps ret (Loaded Reck Bomb)"},
    {"Classic",3,"pve dps mm (mm/sv)"},
    {"Classic",3,"pve dps mm (mm/bm)"},
    {"Classic",3,"pve dps mm (mm/sv)"},
    {"Classic",3,"pve dps bm (farmer)"},
    {"Classic",3,"pve dps mm"},
    {"Classic",3,"pvp dps surv"},
    {"Classic",3,"pvp dps mm"},
    {"Classic",3,"pvp dps bm"},
    {"Classic",4,"pve dps combat (swords)"},
    {"Classic",4,"pve dps combat (daggers)"},
    {"Classic",4,"pve dps combat (daggers2)"},
    {"Classic",4,"pve dps combat"},
    {"Classic",4,"pvp dps combat (swords)"},
    {"Classic",4,"pvp dps combat (daggers)"},
    {"Classic",4,"pvp dps combat (daggers2)"},
    {"Classic",4,"pvp dps combat"},
    {"Classic",5,"pve heal disc"},
    {"Classic",5,"pve heal holy"},
    {"Classic",5,"pve dps shadow"},
    {"Classic",5,"pvp dps disc"},
    {"Classic",5,"pvp heal holy"},
    {"Classic",5,"pvp dps shadow"},
    {"Classic",7,"pve dps elem (elemental mastery)"},
    {"Classic",7,"pve dps elem (nature's swiftness)"},
    {"Classic",7,"pve dps elem (force of nature + hand of edward the odd)"},
    {"Classic",7,"pve heal resto (pure)"},
    {"Classic",7,"pve heal resto (melee support resto)"},
    {"Classic",7,"pvp dps elem (nature's swiftness)"},
    {"Classic",7,"pvp dps elem (elemental mastery)"},
    {"Classic",7,"pvp dps elem (elemental mastery)"},
    {"Classic",7,"pvp dps enhan (2hand)"},
    {"Classic",7,"pvp heal resto"},
    {"Classic",8,"pve dps arcane"},
    {"Classic",8,"pve dps fire"},
    {"Classic",8,"pve dps frost (winter’s chill spec)"},
    {"Classic",8,"pve dps frost (frost build for farming)"},
    {"Classic",8,"pve dps frost (frost-arcane)"},
    {"Classic",8,"pve dps frost (fun)"},
    {"Classic",8,"pve dps frost (aoe farm)"},
    {"Classic",8,"pve dps arcane (glass cannon)"},
    {"Classic",8,"pve dps frost"},
    {"Classic",8,"pvp dps frost"},
    {"Classic",8,"pvp dps frost (frosted fun)"},
    {"Classic",8,"pvp dps arcane (venruki)"},
    {"Classic",9,"pve dps demo (ds/ruin)"},
    {"Classic",9,"pve dps demo (succubus sacrifice)"},
    {"Classic",9,"pve dps dest (imp lord)"},
    {"Classic",9,"pve dps demo (sm/ruin)"},
    {"Classic",9,"pve dps affli"},
    {"Classic",9,"pvp dps demo (sl)"},
    {"Classic",9,"pvp dps demo (soul link/ shadowburn)"},
    {"Classic",9,"pvp dps demo (soul link/ nightfall)"},
    {"Classic",9,"pvp dps affli (sm/ruin)"},
    {"Classic",9,"pvp dps affli (drakedog)"},
    {"Classic",9,"pvp dps affli (sm/ruin)"},
    {"Classic",9,"pvp dps destro (conflagrate)"},
    {"Classic",11,"pve dps feral"},
    {"Classic",11,"pve dps feral (dps/tank hybrid)"},
    {"Classic",11,"pve dps resto (swiftmend spec)"},
    {"Classic",11,"pve dps resto (regrowth spec bear aoe farm)"},
    {"Classic",11,"pve dps resto (resto-balance)"},
    {"Classic",11,"pvp dps resto (swiftmend / feral charge)"},
    {"Classic",11,"pvp dps resto"},
    {"Classic",11,"pvp dps feral (heart of the wild / ns)"},
    {"Classic",11,"pvp dps balance (moonfury)"},
    {"Classic",11,"pvp dps balance (boomkin)"},
    {"TBC",1,"pve arms"},
    {"TBC",1,"pve fury"},
    {"TBC",1,"pve prot"},
    {"TBC",1,"pvp arms"},
    {"TBC",1,"pvp fury"},
    {"TBC",1,"pvp prot"},
    {"TBC",1,"fury slam"},
    {"TBC",1,"arms poleaxes"},
    {"TBC",1,"arms maces"},
    {"TBC",1,"arms swords"},
    {"TBC",2,"pve holy"},
    {"TBC",2,"pve dps ret"},
    {"TBC",2,"pve prot"},
    {"TBC",2,"pve prot"},
    {"TBC",2,"pvp heal holy"},
    {"TBC",2,"pvp holy + ret (shockadin)"},
    {"TBC",2,"pvp holy + prot"},
    {"TBC",2,"pvp dps ret (ret-recko)"},
    {"TBC",2,"pvp dps ret (Loaded Reck Bomb)"},
    {"TBC",2,"pvp dps ret"},
    {"TBC",3,"pve dps mm"},
    {"TBC",3,"pve dps bm"},
    {"TBC",3,"pve survival"},
    {"TBC",3,"pvp dps bm (mortalshots)"},
    {"TBC",3,"pvp dps bm"},
    {"TBC",3,"pvp dps mm"},
    {"TBC",3,"pvp dps surv (scatter+imp rev)"},
    {"TBC",3,"pvp dps surv (max agi)"},
    {"TBC",3,"pvp dps surv (bg)"},
    {"TBC",4,"pve assassination"},
    {"TBC",4,"pve assassination v2"},
    {"TBC",4,"pve dps combat"},
    {"TBC",4,"pve dps combat"},
    {"TBC",4,"pvp dps sub (ambush)"},
    {"TBC",4,"pvp dps sub (backstab+ambush)"},
    {"TBC",4,"pvp dps combat (harp)"},
    {"TBC",4,"pvp dps assa (deep)"},
    {"TBC",4,"pvp dps assa (dual wield)"},
    {"TBC",4,"pvp dps assa (elusive)"},
    {"TBC",4,"pvp dps assa (mutilate)"},
    {"TBC",4,"pvp dps assa (mutilate deep)"},
    {"TBC",4,"pvp dps sub (shadowstep)"},
    {"TBC",4,"pvp dps sub (expose armor)"},
    {"TBC",5,"pve heal disc"},
    {"TBC",5,"pve heal holy"},
    {"TBC",5,"pve dps shadow"},
    {"TBC",5,"pvp dps disc"},
    {"TBC",5,"pvp dps holy"},
    {"TBC",5,"pvp dps shadow"},
    {"TBC",7,"pve dps elem"},
    {"TBC",7,"pve dps enh"},
    {"TBC",7,"pve resto"},
    {"TBC",7,"pve resto"},
    {"TBC",7,"pve resto"},
    {"TBC",7,"pvp dps elem"},
    {"TBC",7,"pvp dps elem"},
    {"TBC",7,"pvp dps elem"},
    {"TBC",7,"pvp dps enhan"},
    {"TBC",7,"pvp dps enhan"},
    {"TBC",7,"pvp dps enhan"},
    {"TBC",7,"pvp heal resto"},
    {"TBC",7,"pvp heal resto"},
    {"TBC",7,"pvp dps enhan (shock)"},
    {"TBC",8,"pve dps arcane"},
    {"TBC",8,"pve dps fire"},
    {"TBC",8,"pve dps frost"},
    {"TBC",8,"pvp dps arcane"},
    {"TBC",8,"pvp dps arcane"},
    {"TBC",8,"pvp dps arcane (missiles)"},
    {"TBC",8,"pvp dps fire"},
    {"TBC",8,"pvp dps fire"},
    {"TBC",8,"pvp dps frost"},
    {"TBC",8,"pvp dps (frostfire)"},
    {"TBC",8,"pvp dps arcane (pom + pyro)"},
    {"TBC",9,"pve dps destro"},
    {"TBC",9,"pve dps destro"},
    {"TBC",9,"pve dps affli"},
    {"TBC",9,"pvp dps affli (shadowburn)"},
    {"TBC",9,"pvp dps affli"},
    {"TBC",9,"pvp dps demo"},
    {"TBC",9,"pvp dps demo"},
    {"TBC",9,"pvp dps demo"},
    {"TBC",9,"pvp dps destro"},
    {"TBC",9,"pvp dps destro"},
    {"TBC",9,"pvp dps destro"},
    {"TBC",9,"pvp dps destro (instant bolts+shadowfury)"},
    {"TBC",9,"pvp dps destro (instant bolts+siphon life)"},
    {"TBC",9,"pvp dps demo"},
    {"TBC",9,"pvp dps affli"},
    {"TBC",11,"pve dps balance"},
    {"TBC",11,"pve dps feral cat"},
    {"TBC",11,"pve dps feral tank"},
    {"TBC",11,"pve resto"},
    {"TBC",11,"pvp dps balance"},
    {"TBC",11,"pvp dps balance"},
    {"TBC",11,"pvp dps balance (mana reg)"},
    {"TBC",11,"pvp resto (high range)"},
    {"TBC",11,"pvp resto (low range)"},
    {"TBC",11,"pvp resto (tree of life)"},
    {"TBC",11,"pvp resto (restokin)"},
    {"TBC",11,"pvp feral cat"},
    {"TBC",11,"pvp feral (mangler)"},
    {"WotLK",1,"pve arms"},
    {"WotLK",1,"pve fury"},
    {"WotLK",1,"pve prot"},
    {"WotLK",1,"pvp arms"},
    {"WotLK",1,"pvp fury"},
    {"WotLK",1,"pvp prot"},
    {"WotLK",2,"Ret Pvp"},
    {"WotLK",2,"Prot Pvp"},
    {"WotLK",2,"Holy Pvp"},
    {"WotLK",2,"Ret Pve"},
    {"WotLK",2,"Prot Pve"},
    {"WotLK",2,"Holy Pve"},
    {"WotLK",3,"BM Pvp"},
    {"WotLK",3,"MM Pvp"},
    {"WotLK",3,"Surv Pvp"},
    {"WotLK",3,"BM Pve"},
    {"WotLK",3,"MM Pve"},
    {"WotLK",3,"Surv Pve"},
    {"WotLK",4,"Assassination Pvp"},
    {"WotLK",4,"Combat Pvp"},
    {"WotLK",4,"Subtlety Pvp"},
    {"WotLK",4,"Assassination Pve"},
    {"WotLK",4,"Combat Pve"},
    {"WotLK",4,"Subtlety Pve"},
    {"WotLK",5,"Shadow PvE"},
    {"WotLK",5,"Shadow PvP"},
    {"WotLK",5,"Disc PvE"},
    {"WotLK",5,"Disc PvE renew build"},
    {"WotLK",5,"Holy PvE"},
    {"WotLK",5,"Holy PvP"},
    {"WotLK",6,"Blood Pvp"},
    {"WotLK",6,"Unholy Pvp"},
    {"WotLK",6,"Frost Pvp"},
    {"WotLK",6,"Blood Pve"},
    {"WotLK",6,"Unholy Pve"},
    {"WotLK",6,"Frost Pve"},
    {"WotLK",7,"Enh Pvp"},
    {"WotLK",7,"Ele Pvp"},
    {"WotLK",7,"Resto Pvp"},
    {"WotLK",7,"Enh Pve"},
    {"WotLK",7,"Ele Pve"},
    {"WotLK",7,"Resto Pve"},
    {"WotLK",8,"Arcane Pvp"},
    {"WotLK",8,"Fire Pvp"},
    {"WotLK",8,"Frost Pvp"},
    {"WotLK",8,"Arcane Pve"},
    {"WotLK",8,"Fire Pve"},
    {"WotLK",8,"Frost Arcane Pve"},
    {"WotLK",9,"Affli CoE Pvp"},
    {"WotLK",9,"Affli CoA Pvp"},
    {"WotLK",9,"Destro Pvp"},
    {"WotLK",9,"Demo Pve"},
    {"WotLK",9,"Affli Pve"},
    {"WotLK",9,"Destro Pve"},
    {"WotLK",9,"Demo Pve"},
    {"WotLK",11,"Feral shred Pvp"},
    {"WotLK",11,"Feral 1v1 Pvp"},
    {"WotLK",11,"Balance Pvp"},
    {"WotLK",11,"Resto Pvp"},
    {"WotLK",11,"Feral dps Pve"},
    {"WotLK",11,"Feral Tank Pve"},
    {"WotLK",11,"Balance Pve"},
    {"WotLK",11,"Restro Pve"},
}
